import streamlit as st
import yfinance as yf
import pandas as pd

st.set_page_config(page_title="V15 NIFTY500", layout="wide")

# PREMIUM UI CSS - V14 Wala
st.markdown("""
<style>
.stApp {background: #0a0e1a;}
h1 {background: linear-gradient(90deg, #00D1FF, #7000FF); -webkit-background-clip: text; -webkit-text-fill-color: transparent; font-weight:900; font-size:42px!important;}
div[data-testid="metric-container"] {background: linear-gradient(135deg, #1a1f35, #12162a); border:1px solid #2a3a5c; border-radius:15px; padding:15px;}
.stButton>button {background: linear-gradient(90deg, #00D1FF, #7000FF); color:white; border:none; border-radius:12px; padding:12px 25px; font-weight:700; width:100%;}
.premium-card {background: linear-gradient(135deg, #1a1f35, #12162a); border:1px solid #2a3a5c; border-radius:15px; padding:20px; margin:10px 0;}
.buy-card {border-left:5px solid #00ff88;}
.hold-card {border-left:5px solid #ffaa00;}
.sell-card {border-left:5px solid #ff0040;}
</style>
""", unsafe_allow_html=True)

st.markdown("<h1>FinTrade V15 - NIFTY 100 + 500 💎</h1>", unsafe_allow_html=True)
st.markdown("<p style=color:#8892b0>V13.1 INDIAN FIX + PREMIUM UI + NIFTY 100/500 SCANNER</p>", unsafe_allow_html=True)

TICKER_MAP = {"ZOMATO":"ETERNAL.NS","PAYTM":"PAYTM.NS","RELIANCE":"RELIANCE.NS","CUPID":"CUPID.NS","GAIL":"GAIL.NS"}
NAME_MAP = {"ETERNAL.NS":"ZOMATO","RELIANCE.NS":"RELIANCE"}

# NIFTY 50
NIFTY50 = ["RELIANCE.NS","TCS.NS","INFY.NS","HDFCBANK.NS","ICICIBANK.NS","BHARTIARTL.NS","ITC.NS","SBIN.NS","LT.NS","KOTAKBANK.NS","AXISBANK.NS","BAJFINANCE.NS","ASIANPAINT.NS","MARUTI.NS","TITAN.NS","SUNPHARMA.NS","ULTRACEMCO.NS","NTPC.NS","POWERGRID.NS","ONGC.NS","WIPRO.NS","HCLTECH.NS","M&M.NS","ADANIENT.NS","ADANIPORTS.NS","COALINDIA.NS","HINDALCO.NS","JSWSTEEL.NS","TATASTEEL.NS","GRASIM.NS","CIPLA.NS","DRREDDY.NS","DIVISLAB.NS","EICHERMOT.NS","BAJAJ-AUTO.NS","HEROMOTOCO.NS","BRITANNIA.NS","NESTLEIND.NS","TATACONSUM.NS","HINDUNILVR.NS","GAIL.NS","BPCL.NS","CUPID.NS","ETERNAL.NS","PAYTM.NS","SBILIFE.NS","HDFCLIFE.NS","ICICIPRULI.NS","BAJAJFINSV.NS"]

# NIFTY 100 = NIFTY50 + NEXT 50
NIFTY100 = NIFTY50 + ["INDUSINDBK.NS","BANDHANBNK.NS","FEDERALBNK.NS","IDFCFIRSTB.NS","PNB.NS","BANKBARODA.NS","CANBK.NS","AUROPHARMA.NS","LUPIN.NS","BIOCON.NS","TORNTPHARM.NS","ZYDUSLIFE.NS","DABUR.NS","GODREJCP.NS","MARICO.NS","COLPAL.NS","BERGEPAINT.NS","PIDILITIND.NS","HAVELLS.NS","VOLTAS.NS","CROMPGREAV.NS","DIXON.NS","AMBUJACEM.NS","ACC.NS","SHREECEM.NS","SAIL.NS","NMDC.NS","HINDPETRO.NS","INDIANB.NS","MUTHOOTFIN.NS","PEL.NS","RECLTD.NS","PFC.NS","IRCTC.NS","ZOMATO.NS","NYKAA.NS","PAYTM.NS","POLYCAB.NS","DLF.NS","GODREJPROP.NS","OBEROIRLTY.NS","PHOENIXLTD.NS","INDIGO.NS","TATAMOTORS.NS","ASHOKLEY.NS","BALKRISIND.NS","MRF.NS","BOSCHLTD.NS","SIEMENS.NS"]

# NIFTY 500 TOP 200 (Full 500 heavy hai, Top 200 se 500 ka coverage)
NIFTY500 = NIFTY100 + ["AARTIIND.NS","ABB.NS","ABBOTINDIA.NS","ABCAPITAL.NS","ABFRL.NS","ADANIGREEN.NS","ADANIPOWER.NS","ATGL.NS","ALKEM.NS","AMARAJABAT.NS","APOLLOHOSP.NS","APOLLOTYRE.NS","ASHOKLEY.NS","ASTRAL.NS","ATUL.NS","AUBANK.NS","BAJAJHLDNG.NS","BAJAJELEC.NS","BALKRISIND.NS","BATAINDIA.NS","BEL.NS","BHARATFORG.NS","BHEL.NS","BIKAJI.NS","BSE.NS","BSOFT.NS","CAMS.NS","CDSL.NS","CESC.NS","CGPOWER.NS","CHAMBLFERT.NS","CHOLAFIN.NS","COFORGE.NS","CONCOR.NS","COROMANDEL.NS","CRAFTSMAN.NS","CUMMINSIND.NS","DALBHARAT.NS","DEEPAKNTR.NS","DELHIVERY.NS","DEVYANI.NS","DMART.NS","DRREDDY.NS","EICHERMOT.NS","ELGIEQUIP.NS","ESCORTS.NS","EXIDEIND.NS","FORTIS.NS","GLAND.NS","GLENMARK.NS","GNFC.NS","GODREJIND.NS","GRANULES.NS","HAL.NS","HDFCAMC.NS","HINDCOPPER.NS","HINDPETRO.NS","ICICIBANK.NS","IDFC.NS","IIFL.NS","INDHOTEL.NS","INDIAMART.NS","INDIGO.NS","INDUSTOWER.NS","INFY.NS","IOC.NS","IPCALAB.NS","IRFC.NS","ITC.NS","JINDALSTEL.NS","JKCEMENT.NS","JSWENERGY.NS","JUBLFOOD.NS","KAJARIACER.NS","KANSAINER.NS","KEI.NS","KPITTECH.NS","LALPATHLAB.NS","LAURUSLABS.NS","LICHSGFIN.NS","LTIM.NS","LTTS.NS","MANAPPURAM.NS","MFSL.NS","MGL.NS","MOTHERSON.NS","MPHASIS.NS","MRF.NS","MUTHOOTFIN.NS","NAM-INDIA.NS","NATIONALUM.NS","NAUKRI.NS","NAVINFLUOR.NS","NESTLEIND.NS","NHPC.NS","NLCINDIA.NS","NMDC.NS","NTPC.NS","OBEROIRLTY.NS","OFSS.NS","ONGC.NS","PAGEIND.NS","PERSISTENT.NS","PETRONET.NS","PFIZER.NS","PIIND.NS","PNB.NS","POWERGRID.NS","PVRINOX.NS","RAMCOCEM.NS","RBLBANK.NS","RECLTD.NS","RELAXO.NS","SBICARD.NS","SRF.NS","SUNPHARMA.NS","SUNTV.NS","TATACHEM.NS","TATACOMM.NS","TATAPOWER.NS","TCS.NS","TECHM.NS","TITAN.NS","TORNTPOWER.NS","TRENT.NS","TV
